import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from app.database import Base, engine
from app import models
from app.routes import auth_routes, user_routes, attendance_routes, qr_routes, admin_routes

app = FastAPI(title="Face + ID Attendance System")

# ✅ Enable CORS for cross-device access (Laptop ↔ Phone)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ✅ Create DB tables
Base.metadata.create_all(bind=engine)

# ✅ Include route files
app.include_router(auth_routes.router)
app.include_router(user_routes.router)
app.include_router(attendance_routes.router)
app.include_router(admin_routes.router)
app.include_router(qr_routes.router)

# =========================
# ✅ Static & QR Folder Setup
# =========================

# Get backend base directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))            # e.g. .../backend/app
ROOT_DIR = os.path.dirname(os.path.dirname(BASE_DIR))            # e.g. .../face-id-attendance

# Frontend static folder (HTML, CSS, JS)
FRONTEND_STATIC = os.path.join(ROOT_DIR, "frontend", "static")

# QR image folder (generated by backend)
QR_FOLDER = os.path.join(ROOT_DIR, "frontend", "static", "qr")

# Ensure QR folder exists
os.makedirs(QR_FOLDER, exist_ok=True)

# ✅ Mount static routes
# Frontend static files (Bootstrap, HTML, JS, etc.)
app.mount("/", StaticFiles(directory="C:/face-id-attendance/frontend/static", html=True), name="static")


# QR folder mount for image access
app.mount("/qr", StaticFiles(directory=QR_FOLDER), name="qr_images")

# ✅ Root route
@app.get("/")
def root():
    return {"message": "Face + ID Attendance API running successfully 🚀"}
